blacklist nvidia
blacklist nvidia_modeset
blacklist nvidia_uvm
blacklist nvidia_drm

install nvidia /usr/bin/false
install nvidia_modeset /usr/bin/false
install nvidia_uvm /usr/bin/false
install nvidia_drm /usr/bin/false
